using DjApplication3.DataSource;
using DjApplication3.Infrastructure;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.Web.WebView2.Core;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Text.Json;

namespace DjApplication3.WinUI.Views
{
    public sealed partial class MainView
    {
        private async void YtMusicButton_Click(object sender, RoutedEventArgs e)
        {
            if (YtMusicDataSource.isConnected())
            {
                YtMusicDataSource.removeConnect();
                UpdateYtMusicButton();
                return;
            }

            LoginPanel.Visibility = Visibility.Visible;
            try
            {
                var version = CoreWebView2Environment.GetAvailableBrowserVersionString();
                if (string.IsNullOrWhiteSpace(version))
                {
                    throw new InvalidOperationException("Runtime Microsoft Edge WebView2 introuvable.");
                }

                if (_loginWebView == null)
                {
                    _loginWebView = new WebView2();
                    LoginWebViewHost.Children.Add(_loginWebView);
                }

                if (_loginWebView.CoreWebView2 == null)
                {
                    await _loginWebView.EnsureCoreWebView2Async();
                }

                var coreWebView = _loginWebView.CoreWebView2;
                if (coreWebView == null)
                {
                    throw new InvalidOperationException("WebView2 n'est pas pret.");
                }

                coreWebView.Navigate("https://accounts.google.com/ServiceLogin?continue=https://music.youtube.com/");
            }
            catch (COMException ex)
            {
                LoginPanel.Visibility = Visibility.Collapsed;
                ViewModel.Status = $"WebView2 indisponible: {ex.Message}";
                AppLogger.Error(ex, "WebView2 unavailable for Youtube Music login");
            }
            catch (Exception ex)
            {
                LoginPanel.Visibility = Visibility.Collapsed;
                ViewModel.Status = $"Ouverture Youtube Music impossible: {ex.Message}";
                AppLogger.Error(ex, "Open Youtube Music login failed");
            }
        }

        private async void ContinueYtMusicButton_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                if (_loginWebView?.CoreWebView2 == null)
                {
                    ViewModel.Status = "WebView2 n'est pas prêt.";
                    return;
                }

                var cookieManager = _loginWebView.CoreWebView2.CookieManager;
                var cookies = new List<CoreWebView2Cookie>();
                foreach (var url in new[]
                {
                    "https://music.youtube.com",
                    "https://www.youtube.com",
                    "https://youtube.com",
                    "https://accounts.google.com",
                    "https://google.com"
                })
                {
                    cookies.AddRange(await cookieManager.GetCookiesAsync(url));
                }

                cookies = cookies
                    .GroupBy(c => $"{c.Domain}|{c.Path}|{c.Name}")
                    .Select(group => group.First())
                    .ToList();

                if (cookies == null || cookies.Count == 0)
                {
                    ViewModel.Status = "Aucun cookie trouvé. Connecte-toi d'abord.";
                    return;
                }

                var cookieData = cookies.Select(c => new
                {
                    c.Name,
                    c.Value,
                    c.Path,
                    c.Domain
                }).ToList();

                Directory.CreateDirectory(Path.GetDirectoryName(YtMusicDataSource.sessionFile)!);
                File.WriteAllText(YtMusicDataSource.sessionFile, JsonSerializer.Serialize(cookieData));

                var sb = new StringBuilder();
                sb.AppendLine("# Netscape HTTP Cookie File");
                sb.AppendLine("# This file is generated by DjApplication3 - do not edit.");
                foreach (var c in cookies)
                {
                    var flag = c.Domain.StartsWith(".") ? "TRUE" : "FALSE";
                    var secure = c.IsSecure ? "TRUE" : "FALSE";
                    sb.AppendLine($"{c.Domain}\t{flag}\t{c.Path}\t{secure}\t0\t{c.Name}\t{c.Value}");
                }
                File.WriteAllText(YtMusicDataSource.ytdlpCookieFile, sb.ToString());

                LoginPanel.Visibility = Visibility.Collapsed;
                ViewModel.Status = "Connexion Youtube Music réussie.";
                UpdateYtMusicButton();
                await ViewModel.LoadPlaylistsAsync();
            }
            catch (Exception ex)
            {
                ViewModel.Status = $"Connexion Youtube Music impossible: {ex.Message}";
                AppLogger.Error(ex, "Youtube Music cookie export failed");
            }
        }

        private void UpdateYtMusicButton()
            => YtMusicButton.Content = YtMusicDataSource.isConnected()
                ? "Deconnexion Youtube Music"
                : "Connexion Youtube Music";
    }
}
