using DjApplication3.DataSource;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.Web.WebView2.Core;
using System;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Text.Json;

namespace DjApplication3.WinUI.Views
{
    public sealed partial class MainView
    {
        private async void YtMusicButton_Click(object sender, RoutedEventArgs e)
        {
            if (YtMusicDataSource.isConnected())
            {
                YtMusicDataSource.removeConnect();
                UpdateYtMusicButton();
                return;
            }

            LoginPanel.Visibility = Visibility.Visible;
            try
            {
                var version = CoreWebView2Environment.GetAvailableBrowserVersionString();
                if (string.IsNullOrWhiteSpace(version))
                {
                    throw new InvalidOperationException("Runtime Microsoft Edge WebView2 introuvable.");
                }

                if (_loginWebView == null)
                {
                    _loginWebView = new WebView2();
                    LoginWebViewHost.Children.Add(_loginWebView);
                }

                if (_loginWebView.CoreWebView2 == null)
                {
                    await _loginWebView.EnsureCoreWebView2Async();
                }

                var coreWebView = _loginWebView.CoreWebView2;
                if (coreWebView == null)
                {
                    throw new InvalidOperationException("WebView2 n'est pas pret.");
                }

                coreWebView.Navigate("https://accounts.google.com/ServiceLogin?continue=https://music.youtube.com/");
            }
            catch (COMException ex)
            {
                LoginPanel.Visibility = Visibility.Collapsed;
                ViewModel.Status = $"WebView2 indisponible: {ex.Message}";
            }
            catch (Exception ex)
            {
                LoginPanel.Visibility = Visibility.Collapsed;
                ViewModel.Status = $"Ouverture Youtube Music impossible: {ex.Message}";
            }
        }

        private async void ContinueYtMusicButton_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                if (_loginWebView?.CoreWebView2 == null)
                {
                    ViewModel.Status = "WebView2 n'est pas prêt.";
                    return;
                }

                var cookieManager = _loginWebView.CoreWebView2.CookieManager;
                var cookies = await cookieManager.GetCookiesAsync("https://music.youtube.com");
                if (cookies == null || cookies.Count == 0)
                {
                    ViewModel.Status = "Aucun cookie trouvé. Connecte-toi d'abord.";
                    return;
                }

                var cookieData = cookies.Select(c => new
                {
                    c.Name,
                    c.Value,
                    c.Path,
                    c.Domain
                }).ToList();

                File.WriteAllText(YtMusicDataSource.sessionFile, JsonSerializer.Serialize(cookieData));

                var sb = new StringBuilder();
                sb.AppendLine("# Netscape HTTP Cookie File");
                sb.AppendLine("# This file is generated by DjApplication3 - do not edit.");
                foreach (var c in cookies)
                {
                    var flag = c.Domain.StartsWith(".") ? "TRUE" : "FALSE";
                    sb.AppendLine($"{c.Domain}\t{flag}\t{c.Path}\tTRUE\t0\t{c.Name}\t{c.Value}");
                }
                File.WriteAllText(YtMusicDataSource.ytdlpCookieFile, sb.ToString());

                LoginPanel.Visibility = Visibility.Collapsed;
                ViewModel.Status = "Connexion Youtube Music réussie.";
                UpdateYtMusicButton();
                await ViewModel.LoadPlaylistsAsync();
            }
            catch (Exception ex)
            {
                ViewModel.Status = $"Connexion Youtube Music impossible: {ex.Message}";
            }
        }

        private void UpdateYtMusicButton()
            => YtMusicButton.Content = YtMusicDataSource.isConnected()
                ? "Deconnexion Youtube Music"
                : "Connexion Youtube Music";
    }
}
